### ISSUE TITLE
Cannot run minimal build

### ISSUE THREAD

**Issue by VincentBailly** [microsoft/BuildXL#1314] opened 2022-12-05 09:54 UTC
After having installed the prerequisites as listed in the documentation, I did not manage to successfully run the `bxl.cmd -minimal` command.

Running the command does the following:
- First sign-in
   - A Signing UI appears on my screen
   - I entered my smtp
   - I validated the login on my phone authenticator app
-  Second sign-in
   - The console output tells to open the url `https://microsoft.com/devicelogin` and to paste a given code.
   - I did that
   - I validated the login on my phone
- Third login
   - The terminal now asks for the UserName and password for what looks to be a nuget feed.
   - I did not manage to pass this step, I don't know what user-name and password I should use.

I needed a few tries to get to the third step. If I make a mistake during the login process, or I am slower than the 90s timeout then I need to kill the command. If I try to run the command again, I get the following error:
```
D:\BuildXL>bxl.cmd -minimal
Preparing to build.
The BuildXL LKG root does not exist or was not defined by Init.cmd
At D:\BuildXL\Shared\Scripts\Bxl.ps1:202 char:5
+     throw "The BuildXL LKG root does not exist or was not defined by  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The BuildXL LKG...ned by Init.cmd:String) [], RuntimeException
    + FullyQualifiedErrorId : The BuildXL LKG root does not exist or was not defined by Init.cmd
```

Cleaning the repository with `git clean -fdx` does not help recovering from this step.
Closing and reopening the cmd terminal is what I needed to do to get out of this bad state.

The following is not clear to me:
- What am I asked to log into?
- Why do I need to log-in three times with three different methods?
- Why does an open-source project ask me to log into Microsoft services?

**Comment by pgunasekara** [comment] 2022-12-06 22:59
Hi Vincent. The easiest way to build the internal version of buildxl is to make sure you're signed into your machine with Windows Hello to avoid hitting all those auth prompts. The answers to your other questions:

* What am I asked to log into?
    * You're logging into ADO for authentication for package restore/dev cache. If you use Windows hello, you should not see any of these auth prompts.
* Why do I need to log-in three times with three different methods?
    * Not sure why this happened to you. I have not been able to reproduce this on my machine, but I would expect you to get three auth prompts in your browser. I'll look into this for you (although there might not be much we can do on our end because we don't control this)
* Why does an open-source project ask me to log into Microsoft services?
    * Since you're likely building from your work machine, the bxl script will automatically attempt to build the internal version of BuildXL. You can override this by passing the following parameter if you wish to build the public version: `/p:[Sdk.BuildXL]microsoftInternal=0`.

**Comment by pgunasekara** [comment] 2022-12-08 18:26
Closing since Vincent was able to resolve his issue.

**Closed by pgunasekara** 2022-12-08 18:26 UTC
